FROM ubuntu:24.04

VOLUME /opt/robotframework/TestMagazineLuiza/results
VOLUME /opt/robotframework/TestMagazineLuiza/tests

RUN apt-get install -y python3 python3-pip
RUN pip3 install robotframework \
    robotframework-seleniumlibrary